# Setup
title:               June Chan
tagline:             #UA-XXXX-Y
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:
baseurl:
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              June Chan
  url:               https://junecv.github.io
  email:             tumbledrycold [AT] gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
